-- Create the bookings table
create table if not exists bookings (
  id bigint generated by default as identity primary key,
  booking_id text not null,
  customer_name text,
  customer_email text,
  start_time timestamp with time zone,
  end_time timestamp with time zone,
  status text default 'confirmed',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table bookings enable row level security;

-- Create policy to allow Service Role (API) to insert/select
create policy "Enable insert for service role only" on bookings
  for insert with check (true);

create policy "Enable select for service role only" on bookings
  for select using (true);
