import type { Metadata } from "next";
import { Network } from "lucide-react";
import { SolutionPage } from "@/components/commercial/solution-page";

export const metadata: Metadata = { title: "Nitro Strategy", description: "Acompañamiento técnico y comercial para ordenar decisiones de arquitectura, automatización y operación digital.", alternates: { canonical: "https://www.juanarangoecommerce.com/nitro-strategy" } };

export default function NitroStrategyPage() {
  return <SolutionPage eyebrow="Arquitectura · Automatización · Dirección" title="Nitro Strategy" promise="Convierte decisiones técnicas dispersas en una dirección compartida." description="Trabajo con tu equipo para entender restricciones, dependencias y prioridades antes de elegir arquitectura, automatizaciones o proveedores." icon={Network} outcomes={["Mapa de sistemas, responsables y dependencias relevantes.", "Decisiones técnicas conectadas con una necesidad del negocio.", "Riesgos y etapas de implementación visibles para el equipo.", "Documentación que permite revisar y sostener lo construido."]} suitableFor={["La operación depende de varias herramientas y nadie ve el recorrido completo.", "Debes tomar una decisión técnica con impacto en varias áreas.", "Existe un equipo que participará en la implementación y validación."]} notFor={["Buscas una garantía de resultados sin acceso al contexto real.", "La necesidad puede resolverse con una pieza aislada y claramente definida.", "No hay responsables disponibles para validar decisiones y operación."]} steps={[{ title: "Descubrimiento", description: "Reunimos objetivos, restricciones, sistemas y responsables." }, { title: "Diseño", description: "Planteamos opciones, dependencias y criterios de decisión." }, { title: "Ejecución", description: "Implementamos o acompañamos entregas pequeñas y verificables." }, { title: "Transferencia", description: "Documentamos decisiones y dejamos al equipo con control." }]} />;
}
