import post from './post'
import tiktokEmbed from './tiktokEmbed'
import tag from './tag'
import trending from './trending'
import audioResource from './audio-resource'
import advertising from './advertising'
import advertisingShopify from './advertising-shopify'
import appToolCategory from './appToolCategory'
import appTool from './appTool'
import appComparison from './appComparison'
import curso from './curso'
import promptGallery from './promptGallery'
import promptConfig from './promptConfig'
import blogPdfConfig from './blogPdfConfig'
import b2bSolution from './b2bSolution'

export const schemaTypes = [post, tiktokEmbed, tag, trending, audioResource, advertising, advertisingShopify, appToolCategory, appTool, appComparison, curso, promptGallery, promptConfig, blogPdfConfig, b2bSolution]
