import type { Metadata } from "next";
import { CalendarCheck, HeartPulse, ShieldCheck, UserRoundCheck } from "lucide-react";
import { IndustryPage } from "@/components/commercial/industry-page";

export const metadata: Metadata = { title: "Soluciones digitales para clínicas", description: "Captación, orientación y agendamiento digital adaptados al recorrido de cada clínica.", alternates: { canonical: "https://www.juanarangoecommerce.com/soluciones/clinicas" } };

export default function ClinicasPage() {
  return <IndustryPage title="Una experiencia digital que acompaña al paciente" highlight="hasta el siguiente paso." description="Organizamos información, captación y agendamiento para que cada persona sepa qué hacer y el equipo conserve el contexto necesario para atenderla." icon={HeartPulse} situations={["Las consultas llegan por varios canales y se responden de forma distinta", "El paciente necesita orientación clara antes de solicitar una cita", "El equipo repite preguntas y pierde contexto entre conversación y agenda"]} modules={[{ title: "Presentación clara de servicios", description: "Una página que organiza tratamientos, preguntas frecuentes y el siguiente paso sin convertir información médica en promesas comerciales.", icon: HeartPulse }, { title: "Captación con contexto", description: "Formularios o conversaciones que recogen la información necesaria para orientar y priorizar cada solicitud.", icon: UserRoundCheck }, { title: "Agendamiento conectado", description: "Un recorrido hacia la agenda disponible, con confirmaciones y responsables definidos según la operación.", icon: CalendarCheck }, { title: "Control y privacidad", description: "Trazabilidad del contacto y tratamiento responsable de la información que la persona decide compartir.", icon: ShieldCheck }]} />;
}
