import type { Metadata } from "next";
import { ShoppingBag } from "lucide-react";
import { SolutionPage } from "@/components/commercial/solution-page";

export const metadata: Metadata = { title: "Consultoría e implementación Shopify", description: "Acompañamiento para diseñar, organizar e implementar una operación ecommerce sobre Shopify.", alternates: { canonical: "https://www.juanarangoecommerce.com/shopify" } };

export default function ShopifyPage() {
  return <SolutionPage eyebrow="Shopify · Operación · Implementación" title="Shopify" promise="Una tienda conectada con la operación que realmente la sostiene." description="Te acompaño a definir el alcance, ordenar catálogo y recorridos, implementar la tienda y conectar las herramientas necesarias sin convertir la plataforma en la estrategia." icon={ShoppingBag} outcomes={["Alcance y prioridades definidos antes de construir.", "Catálogo, navegación y compra organizados alrededor del cliente.", "Integraciones elegidas según la operación, no por acumulación.", "Entrega documentada para que el equipo conserve el control."]} suitableFor={["Estás preparando una tienda nueva o una migración y necesitas ordenar decisiones.", "Tu tienda existe, pero el recorrido y la operación no están bien conectados.", "Tienes un equipo responsable de catálogo, pedidos y atención."]} notFor={["Buscas una promesa de crecimiento sin revisar oferta, datos ni operación.", "Necesitas únicamente una pieza visual aislada.", "No existe capacidad para mantener catálogo, pedidos o atención después de la entrega."]} steps={[{ title: "Contexto", description: "Revisamos oferta, catálogo, canales, equipo y dependencias actuales." }, { title: "Arquitectura", description: "Definimos estructura, integraciones y prioridades antes de implementar." }, { title: "Construcción", description: "Trabajamos por entregas verificables sobre el alcance acordado." }, { title: "Transferencia", description: "Probamos el recorrido y dejamos documentación para el equipo." }]} />;
}
